---
apt_packages:
  - ansible
  - ansible-lint
  - cmake
  - htop
  - polybar
  - rofi
  - git
  - zsh
  - curl
  - pkg-config
  - libfreetype6-dev
  - libfontconfig1-dev
  - libxcb-xfixes0-dev
  - libxkbcommon-dev
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - picom
  - hsetroot

dotfiles:
  home: "~/"
  i3: "~/.config/i3/"
  polybar: "~/.config/polybar"
  rofi: "~/.config/rofi"
  picom: "~/.config/picom"
  alacritty: "~/.config/alacritty"
  oh_my_zsh:
    plugins_dest: "custom/plugins"
