---
apt_packages:
  - ansible
  - ansible-lint
  - cmake
  - htop
  - polybar
  - rofi
  - git
  - zsh
  - curl
  - pkg-config
  - libfreetype6-dev
  - libfontconfig1-dev
  - libxcb-xfixes0-dev
  - libxkbcommon-dev
  - build-essential
  - libssl-dev
  - zlib1g-dev
  - libbz2-dev
  - libreadline-dev
  - libsqlite3-dev
  - libncursesw5-dev
  - xz-utils
  - tk-dev
  - libxml2-dev
  - libxmlsec1-dev
  - libffi-dev
  - liblzma-dev
  - picom
  - hsetroot
  - xclip
  - tmux
  - tmuxp
  - feh
  - jq
  - unzip
  - coreutils
  - tlp
  - tlp-rdw
  - xapt
  - xserver-xorg-input-libinput

dotfiles:
  home: "~/"
  i3: "~/.config/i3/"
  polybar: "~/.config/polybar"
  rofi: "~/.config/rofi"
  picom: "~/.config/picom"
  tlp: "/etc/"
  alacritty: "~/.config/alacritty"
  gtk:
    versions:
      three: "~/.config/gtk-3.0"
      two: "~/.gtkrc-2.0"
    themes: "~/.local/share/themes"
  oh_my_zsh:
    plugins_dest: "custom/plugins"
    themes_dest: "themes"

asdf:
  plugins:
    - name: "python"
      repository: ""
    - name: "golang"
      repository: "https://github.com/kennyp/asdf-golang.git"
    - name: "nodejs"
      repository: "https://github.com/asdf-vm/asdf-nodejs.git"
    - name: "exa"
      repository: "https://github.com/nyrst/asdf-exa.git"
    - name: "fd"
      repository: ""
    - name: "firebase"
      repository: "https://github.com/jthegedus/asdf-firebase"
    - name: "gcloud"
      repository: "https://github.com/jthegedus/asdf-gcloud"
    - name: "helm"
      repository: "https://github.com/Antiarchitect/asdf-helm.git"
    - name: "k9s"
      repository: "https://github.com/looztra/asdf-k9s"
    - name: "kubectl"
      repository: "https://github.com/asdf-community/asdf-kubectl.git"
    - name: "lua"
      repository: "https://github.com/Stratus3D/asdf-lua.git"
    - name: "minikube"
      repository: "https://github.com/alvarobp/asdf-minikube.git"
    - name: "nerdctl"
      repository: "https://github.com/dmpe/asdf-nerdctl.git"
    - name: "protoc"
      repository: "https://github.com/paxosglobal/asdf-protoc.git"
    - name: "protoc-gen-go-grpc"
      repository: "https://github.com/pbr0ck3r/asdf-protoc-gen-go-grpc.git"
    - name: "shellcheck"
      repository: "https://github.com/luizm/asdf-shellcheck.git"
    - name: "shfmt"
      repository: "https://github.com/luizm/asdf-shfmt.git"
    - name: "terraform"
      repository: "https://github.com/asdf-community/asdf-hashicorp.git"
    - name: "terragrunt"
      repository: "https://github.com/ohmer/asdf-terragrunt"
    - name: "1password-cli"
      repository: "https://github.com/NeoHsu/asdf-1password-cli.git"
    - name: "awscli"
      repository: "https://github.com/MetricMike/asdf-awscli.git"
    - name: "bat"
      repository: ""
    - name: "neovim"
      repository: "https://github.com/richin13/asdf-neovim"
  installs:
    - name: "python"
      version: "3.11.2"
    - name: "python"
      version: "3.9.0"
    - name: "golang"
      version: "latest"
    - name: "nodejs"
      version: "latest"
    - name: "exa"
      version: "latest"
    - name: "gcloud"
      version: "latest"
    - name: "awscli"
      version: "latest:2"
    - name: "neovim"
      version: "nightly"
  globals:
    - name: "python"
      version: "3.9.0"
    - name: "golang"
      version: "latest"
    - name: "nodejs"
      version: "latest"
    - name: "exa"
      version: "latest"
    - name: "gcloud"
      version: "latest"
    - name: "awscli"
      version: "latest:2"
    - name: "neovim"
      version: "nightly"

localhost:
  is_laptop: true
