---
dotfiles:
  home: "~/"
  tmux: "~/.config/tmux"
  nvim: "~/.config/nvim"
  shellthings: "~/.config/shellthings"
  oh_my_zsh:
    plugins_dest: "custom/plugins"
    themes_dest: "themes"

asdf:
  extra_env: ""
  plugins:
    - name: "neovim"
      repository: "https://github.com/richin13/asdf-neovim.git"
    - name: "lazygit"
      repository: "https://github.com/nklmilojevic/asdf-lazygit.git"
    - name: "nodejs"
      repository: "https://github.com/asdf-vm/asdf-nodejs.git"
    - name: "k9s"
      repository: "https://github.com/looztra/asdf-k9s"
  installs:
    - name: "neovim"
      version: "0.9.1"
    - name: "lazygit"
      version: "latest"
    - name: "nodejs"
      version: "16.20.0"
    - name: "k9s"
      version: "0.27.4"
  globals:
    - name: "neovim"
      version: "0.9.1"
    - name: "lazygit"
      version: "latest"
    - name: "nodejs"
      version: "16.20.0"
    - name: "k9s"
      version: "0.27.4"

external_bins:
  - name: "zoxide"
    source: "https://github.com/ajeetdsouza/zoxide/releases/download/v0.9.1/zoxide-0.9.1-x86_64-unknown-linux-musl.tar.gz"
    location: "zoxide"
    type: "archive"
    extra_opts: []
  - name: "fd"
    source: "https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-unknown-linux-musl.tar.gz"
    location: "fd-v8.7.0-x86_64-unknown-linux-musl/fd"
    type: "archive"
    extra_opts:
      - --strip-components=1
  - name: "exa"
    source: "https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-musl-v0.10.1.zip"
    location: "bin/exa"
    type: "archive"
    extra_opts:
      - "-j"
  - name: "ripgrep"
    source: "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz"
    location: "ripgrep-13.0.0-x86_64-unknown-linux-musl/rg"
    type: "archive"
    extra_opts:
      - --strip-components=1
  - name: "fzf"
    source: "https://github.com/junegunn/fzf/releases/download/0.41.1/fzf-0.41.1-linux_amd64.tar.gz"
    location: "fzf"
    type: "archive"
    extra_opts: []
  - name: "bat"
    source: "https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-v0.23.0-x86_64-unknown-linux-musl.tar.gz"
    location: "bat-v0.23.0-x86_64-unknown-linux-musl/bat"
    type: "archive"
    extra_opts:
      - --strip-components=1

has_root_access: false
zsh_location: "/bin/zsh"
attach_to_profile: false

nvim:
  dist: "work"
