---
dotfiles:
  home: "~/"
  oh_my_zsh:
    plugins_dest: "custom/plugins"
    themes_dest: "themes"

asdf:
  plugins:
    - name: "neovim"
      repository: "https://github.com/richin13/asdf-neovim.git"
  installs:
    - name: "neovim"
      version: "0.9.1"
  globals:
    - name: "neovim"
      version: "0.9.1"

external_bins:
  - name: "fd"
    source: "https://github.com/sharkdp/fd/releases/download/v8.7.0/fd-v8.7.0-x86_64-unknown-linux-musl.tar.gz"
    location: "fd-v8.7.0-x86_64-unknown-linux-musl/fd"
    extra_opts:
      - --strip-components=1
  - name: "exa"
    source: "https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-musl-v0.10.1.zip"
    location: "bin/exa"
    extra_opts:
      - "-j"
  - name: "ripgrep"
    source: "https://github.com/BurntSushi/ripgrep/releases/download/13.0.0/ripgrep-13.0.0-x86_64-unknown-linux-musl.tar.gz"
    location: "ripgrep-13.0.0-x86_64-unknown-linux-musl/rg"
    extra_opts:
      - --strip-components=1
  - name: "fzf"
    source: "https://github.com/junegunn/fzf/releases/download/0.41.1/fzf-0.41.1-linux_amd64.tar.gz"
    location: "fzf"
    extra_opts: []
  - name: "bat"
    source: "https://github.com/sharkdp/bat/releases/download/v0.23.0/bat-v0.23.0-x86_64-unknown-linux-musl.tar.gz"
    location: "bat-v0.23.0-x86_64-unknown-linux-musl/bat"
    extra_opts:
      - --strip-components=1

has_root_access: false
zsh_location: "~/bin/zsh"
