---
- name: tmuxp | Create config dir
  ansible.builtin.file:
    path: "{{ dotfiles.tmuxp }}"
    state: directory
    mode: "0755"

- name: tmuxp | Link config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ dotfiles.tmuxp }}"
    state: link
    force: true
