---
- name: rust | Check if cargo installed
  shell: command -v cargo
  args:
    executable: /bin/zsh
  register: cargo_exists
  ignore_errors: true

- name: rust | Download installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: yes

- name: rust | Install
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
