---
- name: Set up remote workstations
  hosts: remotessh
  roles:
    - role: bin
      tags:
        - bin
    - role: compile
      tags:
        - compile
    - role: zsh
      tags:
        - zsh
    - role: asdf
      tags:
        - asdf
    - role: nvim
      tags:
        - nvim
