---
- name: Install packages via ansible.builtin.apt
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
  become: true

- name: i3 | Download sur5r-keyring .deb
  get_url:
    url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.03.09_all.deb
    dest: /tmp/sur5r-keyring.deb
    checksum: "sha256:2c2601e6053d5c68c2c60bcd088fa9797acec5f285151d46de9c830aaba6173c"

- name: i3 | Install sur5r-keyring package
  apt:
    deb: /tmp/sur5r-keyring.deb

- name: i3 | Add apt source
  apt_repository: repo="deb [signed-by=/usr/share/keyrings/sur5r-keyring.gpg] http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
  become: true

- name: i3 | Install
  ansible.builtin.apt:
    update_cache: true
    pkg: i3
    state: latest
  become: true

- name: vscode | Install dependencies
  ansible.builtin.apt:
    name: "{{ vscode.apt_deps }}"
    state: present
  become: true

- name: Create APT keyrings dir
  become: true
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    mode: "u=rwx,go=rx"

- name: vscode | Install apt key
  become: true
  ansible.builtin.get_url:
    url: "{{ vscode.mirror }}/keys/microsoft.asc"
    dest: "/etc/apt/keyrings/"
    mode: "u=rw,go=r"
    force: yes

- name: vscode | Install apt repo
  become: true
  apt_repository:
    repo: >-
      deb [arch=amd64 trusted=yes signed-by=/etc/apt/keyrings/microsoft.asc] {{ vscode.mirror }}/repos/code stable main
    filename: vscode
    state: present

- name: vscode | Install code
  become: true
  ansible.builtin.apt:
    name: "code"
    state: present

- name: chrome | Add gpg signing key
  become: true
  ansible.builtin.get_url:
    url: "{{ chrome.gpg_key }}"
    dest: "/etc/apt/keyrings/chrome.pub"
    mode: "u=rw,go=r"
    force: yes

- name: chrome | Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 trusted=yes signed-by=/etc/apt/keyrings/chrome.pub] {{ chrome.repository }} stable main
    state: "present"
    filename: "{{ chrome.name }}"
    update_cache: yes

- name: chrome | Install
  become: true
  ansible.builtin.apt:
    name: "{{ chrome.apt_name }}"
    state: "present"
    update_cache: yes

- name: mullvad | Add apt key
  become: true
  apt_key:
    url: "https://repository.mullvad.net/deb/mullvad-keyring.asc"
    state: present

- name: mullvad | Add repository
  become: true
  apt_repository:
    repo: deb https://repository.mullvad.net/deb/stable noble main
    state: present

- name: mullvad | Install
  become: true
  ansible.builtin.apt:
    name: "mullvad-vpn"
    state: "present"
    update_cache: yes

- name: firefox | Add apt key
  become: true
  apt_key:
    url: "https://packages.mozilla.org/apt/repo-signing-key.gpg"
    state: present

- name: firefox | Add repository
  become: true
  apt_repository:
    repo: deb https://packages.mozilla.org/apt mozilla main
    state: present

- name: firefox | Set APT priority for Mozilla packages
  become: true
  copy:
    dest: /etc/apt/preferences.d/mozilla
    content: |
      Package: *
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000
    owner: root
    group: root
    mode: '0644'

- name: firefox | Install
  become: true
  ansible.builtin.apt:
    name: "firefox"
    state: "present"
    update_cache: yes

