---
- name: Install packages via ansible.builtin.apt
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
  become: true

- name: i3 | Download package
  shell: >
    /usr/lib/apt/apt-helper download-file https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb /tmp/keyring.deb SHA256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734
  changed_when: false

- name: i3 | Install keyring.deb
  apt: deb=/tmp/keyring.deb
  become: true

- name: i3 | Add apt source
  apt_repository: repo="deb http://debian.sur5r.net/i3/ {{ ansible_distribution_release }} universe"
  become: true

- name: i3 | Install
  ansible.builtin.apt:
    update_cache: true
    pkg: i3
    state: latest
  become: true

- name: vscode | Install dependencies
  ansible.builtin.apt:
    name: "{{ vscode.apt_deps }}"
    state: present
  become: true

- name: Create APT keyrings dir
  become: true
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    state: directory
    mode: "u=rwx,go=rx"

- name: vscode | Install apt key
  become: true
  ansible.builtin.get_url:
    url: "{{ vscode.mirror }}/keys/microsoft.asc"
    dest: "/etc/apt/keyrings/"
    mode: "u=rw,go=r"
    force: yes

- name: vscode | Install apt repo
  become: true
  apt_repository:
    repo: >-
      deb [arch=amd64 trusted=yes signed-by=/etc/apt/keyrings/microsoft.asc] {{ vscode.mirror }}/repos/code stable main
    filename: vscode
    state: present

- name: vscode | Install code
  become: true
  ansible.builtin.apt:
    name: "code"
    state: present

- name: chrome | Add gpg signing key
  become: true
  ansible.builtin.get_url:
    url: "{{ chrome.gpg_key }}"
    dest: "/etc/apt/keyrings/chrome.pub"
    mode: "u=rw,go=r"
    force: yes

- name: chrome | Add repository
  become: true
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64 trusted=yes signed-by=/etc/apt/keyrings/chrome.pub] {{ chrome.repository }} stable main
    state: "present"
    filename: "{{ chrome.name }}"
    update_cache: yes

- name: chrome | Install
  become: true
  ansible.builtin.apt:
    name: "{{ chrome.apt_name }}"
    state: "present"
    update_cache: yes

- name: mullvad | Add apt key
  become: true
  apt_key:
    url: "https://repository.mullvad.net/deb/mullvad-keyring.asc"
    state: present

- name: mullvad | Add repository
  become: true
  apt_repository:
    repo: deb https://repository.mullvad.net/deb/stable noble main
    state: present

- name: mullvad | Install
  become: true
  ansible.builtin.apt:
    name: "mullvad-vpn"
    state: "present"
    update_cache: yes
