---
- name: asdf | Installs asdf
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "{{ dotfiles.home }}/.asdf"
    update: false
    force: true
    version: v0.11.3

- name: asdf | Install plugins
  ansible.builtin.shell: "{{ asdf.extra_env }} asdf plugin-add {{ item.name }} {{ item.repository }}"
  args:
    creates: ".asdf/plugins/{{ item.name }}"
    chdir: "{{ ansible_user_dir }}"
    executable: /bin/zsh
  loop: "{{ asdf.plugins }}"

- name: asdf | Install tools
  ansible.builtin.shell: "asdf install {{ item.name }} {{ item.version }}"
  args:
    chdir: "{{ ansible_user_dir }}"
    executable: /bin/zsh
  loop: "{{ asdf.installs }}"

- name: asdf | Set up globals
  ansible.builtin.shell: "asdf global {{ item.name }} {{ item.version }}"
  args:
    chdir: "{{ ansible_user_dir }}"
    executable: /bin/zsh
  loop: "{{ asdf.globals }}"
