---
- name: zsh | Check if omz already installed
  stat:
    path: "{{ (dotfiles.home, '.oh-my-zsh') | path_join }}"
  register: omz_installed

- name: zsh | Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  when: omz_installed.stat.exists == false

- name: zsh | Clone zsh-autocomplete
  ansible.builtin.git:
    repo: "https://github.com/marlonrichert/zsh-autocomplete.git"
    dest: "{{ (dotfiles.home, '.oh-my-zsh', dotfiles.oh_my_zsh.plugins_dest, 'zsh-autocomplete') | path_join }}"
    version: "main"
    update: false

- name: zsh | Clone zsh-syntax-highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "{{ (dotfiles.home, '.oh-my-zsh', dotfiles.oh_my_zsh.plugins_dest, 'zsh-syntax-highlighting') | path_join }}"
    version: "master"
    update: false

- name: zsh | Clone zsh-fzf
  ansible.builtin.git:
    repo: "https://github.com/unixorn/fzf-zsh-plugin.git"
    dest: "{{ (dotfiles.home, '.oh-my-zsh', dotfiles.oh_my_zsh.plugins_dest, 'fzf-zsh-plugin') | path_join }}"
    version: "main"
    update: false

- name: zsh | Link config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.zshrc"
    dest: "{{ (dotfiles.home, '.zshrc') | path_join }}"
    state: link
    force: true

- name: zsh | Change default shell to /bin/zsh
  ansible.builtin.command: "chsh -s /bin/zsh {{ ansible_user_id }}"
  become: true
  when: ansible_user_shell != '/bin/zsh'
