import:
  - ~/.config/alacritty/themes/themes/campbell.yaml

selection:
  save_to_clipboard: true

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: JetBrains Mono
    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    family: JetBrains Mono
    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono
    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 11.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0
