colors:
  # Default colors
  primary:
    background: "0x1a1b26"
    foreground: "0xc0caf5"

  # Normal colors
  normal:
    black: "0x15161e"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xa9b1d6"

  # Bright colors
  bright:
    black: "0x414868"
    red: "0xf7768e"
    green: "0x9ece6a"
    yellow: "0xe0af68"
    blue: "0x7aa2f7"
    magenta: "0xbb9af7"
    cyan: "0x7dcfff"
    white: "0xc0caf5"

  indexed_colors:
    - { index: 16, color: "0xff9e64" }
    - { index: 17, color: "0xdb4b4b" }

selection:
  save_to_clipboard: true

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - tmux

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: JetBrains Mono
    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    family: JetBrains Mono
    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    family: JetBrains Mono
    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 11.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

cursor:
  # Cursor style
  style:
    # Cursor shape
    #
    # Values for `shape`:
    #   - ▇ Block
    #   - _ Underline
    #   - | Beam
    shape: Block

    # Cursor blinking state
    #
    # Values for `blinking`:
    #   - Never: Prevent the cursor from ever blinking
    #   - Off: Disable blinking by default
    #   - On: Enable blinking by default
    #   - Always: Force the cursor to always blink
    blinking: Never

# https://news.ycombinator.com/item?id=27075659
env:
  TERM: xterm-256color
  WINIT_X11_SCALE_FACTOR: "1.0"
