---
- name: Get ncurses
  ansible.builtin.shell: |
    export CXXFLAGS=" -fPIC" CFLAGS=" -fPIC" CPPFLAGS="-I${HOME}/include" LDFLAGS="-L${HOME}/lib"
    curl https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.2.tar.gz -o ncurses-6.2.tar.gz
    tar -xzvf ncurses-6.2.tar.gz
    cd ncurses-6.2
    ./configure --prefix=$HOME 
    make -j
    make install
    cd .. && rm ncurses-6.2.tar.gz && rm -r ncurses-6.2

- name: Install zsh
  ansible.builtin.shell: |
    curl -L https://sourceforge.net/projects/zsh/files/latest/download -o zsh.tar.xz
    mkdir -p zsh && tar xJvf zsh.tar.xz -C zsh --strip-components 1
    cd zsh
    ./configure --prefix=$HOME
    make -j
    make install
    cd .. && rm zsh.tar.xz && rm -r zsh
