---
- name: i3 | Create the i3 config directory
  ansible.builtin.file:
    path: "{{ dotfiles.i3 }}"
    state: directory
    mode: "0755"

- name: i3 | Link wallpaper
  ansible.builtin.file:
    src: "{{ role_path }}/files/tile.png"
    dest: "{{ (dotfiles.i3, 'tile.png') | path_join }}"
    state: link
    force: true

- name: i3 | Link i3 config
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ (dotfiles.i3, 'config') | path_join }}"
    state: link
    force: true
