---
- name: Create spicetify dir
  ansible.builtin.file:
    path: "{{ dotfiles.spicetify.bin }}"
    state: directory

- name: Create spicetify config dir
  ansible.builtin.file:
    path: "{{ dotfiles.spicetify.config }}"
    state: directory

- name: Extract external spicetify binary
  unarchive:
    src: "{{ spicetify.source }}"
    remote_src: yes
    dest: "{{ dotfiles.spicetify.bin }}"

- name: Give permissions to all users to spotify folder
  become: true
  ansible.builtin.file:
    path: /usr/share/spotify
    state: directory
    mode: '0777'

- name: Give permissions to all users to spotify Apps subfolder
  become: true
  ansible.builtin.file:
    path: /usr/share/spotify/Apps
    state: directory
    mode: '0777'
    recurse: true

- name: Clone spicetify themes
  ansible.builtin.git:
    repo: "{{ spicetify.themes.source }}"
    dest: "{{ (dotfiles.spicetify.config, 'Themes') | path_join }}"
    version: "master"
    update: false
