---
- name: polybar | Create config dir
  ansible.builtin.file:
    path: "{{ dotfiles.polybar }}"
    state: directory
    mode: "0755"

- name: polybar | Link config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ dotfiles.polybar }}"
    state: link
    force: true
