---
- name: polybar | Create config dir
  ansible.builtin.file:
    path: "{{ polybar_config_dest }}"
    state: directory
    mode: '0755'

- name: polybar | Link config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ polybar_config_dest }}"
    state: link
    force: yes
