---
- name: Create bin dir
  ansible.builtin.file:
    path: "{{ (dotfiles.home, '.bin') | path_join }}"
    state: directory

- name: Extract external binaries
  unarchive:
    src: "{{ item.source }}"
    remote_src: yes
    dest: "{{ (dotfiles.home, '.bin') | path_join }}"
    mode: "755"
    extra_opts: "{{ item.extra_opts }}"
    include: "{{ item.location }}"
  register: _unarchive
  ignore_errors: true
  loop: "{{ external_bins | selectattr('type', 'equalto', 'archive') }}"

- name: Copy loose binaries
  get_url:
    url: "{{ item.source }}"
    dest: "{{ (dotfiles.home, '.bin', item.name) | path_join }}"
    mode: "755"
  loop: "{{ external_bins | selectattr('type', 'equalto', 'loose') }}"

- name: Copy scripts
  ansible.builtin.synchronize:
    src: "{{ role_path }}/files/"
    dest: "{{ (dotfiles.home, '.bin') | path_join }}"
