---
- name: Reload udev rules
  ansible.builtin.command: udevadm control --reload-rules
  become: true
  changed_when: true
  listen: reload udev rules

- name: Reload systemctl
  command: systemctl daemon-reload
  become: true
  listen: reload systemctl

- name: Reload user systemctl
  command: systemctl --user daemon-reload
  listen: reload user systemctl

- name: Run on-boot
  command: systemctl start on-boot.service
  become: true
  listen: run on-boot oneshot
