---
- name: x11 | Create x11 conf dir
  ansible.builtin.file:
    path: "{{ dotfiles.x11 }}"
    state: directory
  become: true

- name: x11 | Link touchpad config
  ansible.builtin.file:
    src: "{{ role_path }}/files/touchpad.conf"
    dest: "{{ (dotfiles.x11, '90-touchpad.conf') | path_join }}"
    state: link
    force: true
  become: true

- name: x11 | Link Xresources config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.Xresources"
    dest: "{{ (dotfiles.home, '.Xresources') | path_join }}"
    state: link
    force: true
