---
- name: tmux | Clone tmux plugin manager
  ansible.builtin.git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ (dotfiles.home, '.tmux/plugins/tpm') | path_join }}"
    version: "master"
    update: false

- name: tmux | Link config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ dotfiles.home }}/.tmux.conf"
    state: link
    force: true

- name: tmux | Link remote config
  ansible.builtin.file:
    src: "{{ role_path }}/files/.tmux.remote.conf"
    dest: "{{ dotfiles.home }}/.tmux.remote.conf"
    state: link
    force: true

- name: tmux | Link inner config
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux"
    dest: "{{ dotfiles.tmux }}"
    state: link
    force: true
