---
- name: alacritty | Check if alacritty installed
  shell: command -v cargo
  args:
    executable: /bin/zsh
  register: alacritty_exists
  ignore_errors: true

- name: alacritty | Install
  ansible.builtin.shell: "cargo install alacritty"
  args:
    chdir: "{{ ansible_user_dir }}"
    executable: /bin/zsh
  when: alacritty_exists is failed

- name: alacritty | Create config dir
  ansible.builtin.file:
    path: "{{ dotfiles.alacritty }}"
    state: directory
    mode: "0755"

- name: alacritty | Clone alacritty themes
  ansible.builtin.git:
    repo: "https://github.com/alacritty/alacritty-theme"
    dest: "{{ (dotfiles.alacritty, 'themes') | path_join }}"
    version: "master"
    update: false

- name: alacritty | Link config
  ansible.builtin.file:
    src: "{{ role_path }}/files/alacritty.yml"
    dest: "{{ (dotfiles.alacritty, 'alacritty.yml') | path_join }}"
    state: link
    force: true
