---

- name: "create pihole persistence directory"
  become: true
  ansible.builtin.file:
    path: "{{ pihole.persistence_dest }}"
    state: directory

- name: "create docker network"
  docker_network:
    name: "{{ pihole.network }}"
    ipam_config:
      - subnet: 172.3.27.0/24
        gateway: 172.3.27.2
        iprange: 172.3.27.0/26

- name: "setup docker container"
  docker_container:
    name: "pihole"
    image: "{{ pihole.repository.name }}:{{ pihole.repository.tag }}"
    state: started
    restart: yes
    restart_policy: unless-stopped
    networks_cli_compatible: yes
    networks:
      - name: "{{ pihole.network }}"
        ipv4_address: "{{ pihole.ip }}"
    volumes:
      - "{{ pihole.persistence_dest }}:/etc/pihole/"
    env:
      TZ: "Europe/Amsterdam"
      ServerIP: "{{ pihole.ip }}"
      INTERFACE: "{{ pihole.interface }}"
    capabilities:
      - NET_ADMIN
      - SYS_NICE
      - SYS_TIME
    ports:
      - "2180:80"
      - "21443:443"

- name: set DNS resolution
  command: resolvectl dns {{ pihole.interface }} {{ pihole.ip }}
  become: true

- name: create /etc/systemd/resolved.conf.d directory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d
    state: directory
    mode: '0755'

- name: add DNS settings resolv.conf
  become: true
  ansible.builtin.template:
    src: templates/dns_servers.conf.j2
    dest: /etc/systemd/resolved.conf.d/dns_servers.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart service systemd-resolved

